#!/usr/bin/env bash
#
# GamerAI — one-shot VPS bootstrap.
#
# Provisions a fresh Ubuntu 22.04+ VPS to run the GamerAI MVP coordinator
# behind TLS. Idempotent — safe to re-run.
#
# Usage (from the VPS as root):
#
#   curl -sSL https://raw.githubusercontent.com/Hyrumdrums/GamerAI/main/infra/bootstrap.sh \
#     | sudo bash -s -- --domain coordinator.example.com --email you@example.com
#
# Optional flags:
#   --branch <name>    git branch to deploy (default: main)
#   --repo   <url>     git repo URL (default: this repo)
#   --dir    <path>    install directory (default: /opt/gamerai)
#
set -euo pipefail

DOMAIN=""
EMAIL=""
BRANCH="${BRANCH:-main}"
REPO="${REPO:-https://github.com/Hyrumdrums/GamerAI.git}"
INSTALL_DIR="${INSTALL_DIR:-/opt/gamerai}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2 ;;
    --email)  EMAIL="$2"; shift 2 ;;
    --branch) BRANCH="$2"; shift 2 ;;
    --repo)   REPO="$2"; shift 2 ;;
    --dir)    INSTALL_DIR="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,18p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$DOMAIN" ]] && { echo "ERROR: --domain is required" >&2; exit 1; }
[[ -z "$EMAIL"  ]] && { echo "ERROR: --email is required (for Let's Encrypt)" >&2; exit 1; }
[[ "$EUID" -eq 0 ]] || { echo "ERROR: must run as root (use sudo)" >&2; exit 1; }

log() { printf '\033[1;36m[gamerai]\033[0m %s\n' "$*"; }

log "domain=$DOMAIN email=$EMAIL branch=$BRANCH dir=$INSTALL_DIR"

# ---------- 1. base packages ----------
log "installing prerequisites..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
  ca-certificates curl gnupg git openssl ufw

# ---------- 2. firewall ----------
if command -v ufw >/dev/null; then
  log "configuring firewall (allow 22, 80, 443)..."
  ufw --force reset >/dev/null
  ufw default deny incoming >/dev/null
  ufw default allow outgoing >/dev/null
  ufw allow 22/tcp  >/dev/null
  ufw allow 80/tcp  >/dev/null
  ufw allow 443/tcp >/dev/null
  ufw --force enable >/dev/null
fi

# ---------- 3. docker ----------
if ! command -v docker >/dev/null; then
  log "installing Docker Engine + Compose plugin..."
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
fi

# ---------- 4. clone or update repo ----------
log "syncing repo at $INSTALL_DIR..."
if [[ -d "$INSTALL_DIR/.git" ]]; then
  git -C "$INSTALL_DIR" fetch --quiet origin
  git -C "$INSTALL_DIR" checkout --quiet "$BRANCH"
  git -C "$INSTALL_DIR" pull --ff-only --quiet origin "$BRANCH"
else
  git clone --quiet --branch "$BRANCH" "$REPO" "$INSTALL_DIR"
fi

# ---------- 5. env file (preserves existing token on re-run) ----------
ENV_FILE="$INSTALL_DIR/.env.prod"
if [[ ! -f "$ENV_FILE" ]]; then
  log "generating $ENV_FILE..."
  WORKER_TOKEN=$(openssl rand -hex 32)
  cat > "$ENV_FILE" <<EOF
# generated by infra/bootstrap.sh — do not commit
DOMAIN=$DOMAIN
EMAIL=$EMAIL
WORKER_TOKEN=$WORKER_TOKEN
MOCK_INFERENCE=true
EOF
  chmod 600 "$ENV_FILE"
else
  log "$ENV_FILE already exists — leaving in place"
  # keep existing token; refresh domain/email in case they changed
  sed -i "s|^DOMAIN=.*|DOMAIN=$DOMAIN|"  "$ENV_FILE"
  sed -i "s|^EMAIL=.*|EMAIL=$EMAIL|"     "$ENV_FILE"
fi

# ---------- 6. bring services up ----------
log "starting services (this builds images on first run)..."
cd "$INSTALL_DIR"
docker compose \
  --env-file "$ENV_FILE" \
  -f docker-compose.yml \
  -f infra/docker-compose.prod.yml \
  up -d --build

# ---------- 7. summary ----------
TOKEN=$(grep '^WORKER_TOKEN=' "$ENV_FILE" | cut -d= -f2-)
echo
echo "============================================================"
log "deployment complete!"
echo
echo "  Coordinator URL:  https://$DOMAIN"
echo "  Health check:     https://$DOMAIN/health"
echo "  Worker token:     $TOKEN"
echo
echo "  Web UI (private): ssh -L 8080:127.0.0.1:8080 root@<this-host>"
echo "                    then open http://localhost:8080"
echo
echo "  Re-deploy:        $INSTALL_DIR/infra/deploy.sh"
echo "  Logs:             docker compose -f $INSTALL_DIR/docker-compose.yml \\"
echo "                      -f $INSTALL_DIR/infra/docker-compose.prod.yml logs -f"
echo
echo "  NOTE: API is currently OPEN. Before recruiting external workers,"
echo "        enable bearer auth — see infra/README.md."
echo "============================================================"
